Cencosud-X/seki-cloud-components

centrifugo/schema.json
google_postgres/schema.json
redis/schema.json

feat(production) supporting production property in centrifugo, postgres and redis

feat(schemas): added support to production

---

elastic/schema.json

feat(elastic) Add admin_viewer parameter

---

dataproc/schema.json

feat(dataproc) Add initialization_action on cluster config

---

bigquery/componentrc.json

change stream uid

---

elastic/schema.json

feat(elastic) Add new parameters to the schema

---

elastic/schema.json

feat(elasti) Add parameters to the schema

---

elastic/schema.json

feat(elastic) Update schema

---

elastic/schema.json

feat(elastic) Add none parameter

---

elastic/schema.json

feat(elastic) Revert changes

---

elastic/schema.json

feat(elastic) Add min_size to the schema

---

bigquery_sink_connector/schema.json

feat(bigquery_sink_connector) Change topics variable

---

bigquery_sink_connector/schema.json

feat(bigquery_sink_connector) Add commas

---

bigquery_sink_connector/schema.json

feat(bigquery_sink_connector) Update varaibles

---

bigquery_sink_connector/schema.json

feat(bigquery_sink_connector) Delete dataset parameter

---

bigquery_sink_connector/schema.json

feat(bigquery_sink_connector) Change string for number to tasks_max

---

cloudflare_access/componentrc.json

feat:cf-access-cc: fixing the line of owner in componentrc.json file

---

uptime/schema.json

feat(uptime) Add severety type

---

uptime/schema.json

feat(uptime) Enable alerts

---

uptime/schema.json

feat(uptime) Change 2 for 2.0 to HTTP method

---

uptime/schema.json

feat(uptime) Update email schema

---

uptime/schema.json

feat(uptime) Change string for boolean to email

---

uptime/schema.json

feat(uptime) Add environment tag to the jobs

---

uptime/schema.json

feat(uptime) Add enum to environment paremeter

---

elastic/schema.json

feat(elastic) Add required values

---

vertex_ai/schema.json

feat(vertex) Add shielded_instance_config to the schema

---

dataproc/schema.json

feat(dataproc) Add new parameters

---

aws_redis/componentrc.json
aws_redis/icons/icon-white.svg
aws_redis/icons/icon.svg
aws_redis/schema.json
aws_redis/scripts/rollback.js
manifiest.json

feature(aws redis): add module aws redis
